#!/usr/bin/env python3
"""
Tradiesignal :: static site builder
===================================
Wraps the artifact-format pages into complete, standalone HTML documents and
writes a `deploy/` folder you can drag straight into Netlify (or push to a
GitHub repo Netlify watches).

The page builders emit content-only HTML because the Artifact tool supplies the
document skeleton. Netlify does not, so this adds:

  * <!doctype>, <html lang>, <head>, <body>
  * viewport, charset, description, canonical
  * Open Graph and Twitter cards (what a link looks like when someone
    forwards it in a WhatsApp trade group — which is how this spreads)
  * favicon
  * real CTA links instead of on-page anchors

Usage:
    python3 src/build_site.py --domain tradiesignal.com --checkout <stripe-link>
"""

from __future__ import annotations

import argparse
import re
import shutil
from pathlib import Path

SITE = Path("site")
REPORTS = Path("reports")
OUT = Path("deploy")

# Inlined so the pages have zero external asset dependencies.
FAVICON = (
    "data:image/svg+xml,%3Csvg xmlns='http://www3.org/2000/svg' viewBox='0 0 32 32'%3E"
    "%3Crect width='32' height='32' rx='6' fill='%230A1628'/%3E"
    "%3Cpath d='M17.5 4 9 18h5.5L13 28l9-14h-5.5L17.5 4z' fill='%2300E07A'/%3E%3C/svg%3E"
).replace("www3.org", "www.w3.org")

PAGES = {
    "index.html": {
        "src": SITE / "landing.html",
        "title": "Tradiesignal — Find Electrical Work Before Your Competition | Newcastle NSW",
        "desc": "Council approvals, construction certificates and government projects "
                "across the Hunter, scored and delivered weekly. See who's building "
                "and who to call. 14-day free trial.",
        "path": "/",
        "index": True,
    },
    "sample-report/index.html": {
        "src": REPORTS / "report_web.html",
        "title": "Sample Report — Hunter Electrical Opportunity Report | Tradiesignal",
        "desc": "A real issue: every development application, complying development "
                "certificate and construction certificate lodged with the five Hunter "
                "councils, scored and turned into a call list. No sign-up.",
        "path": "/sample-report/",
        "index": True,
    },
    "demo/index.html": {
        "src": SITE / "dashboard.html",
        "title": "Opportunity Dashboard Demo | Tradiesignal",
        "desc": "Live demo of the Tradiesignal opportunity dashboard over real Hunter "
                "construction data.",
        "path": "/demo/",
        "index": False,   # a sales asset, not a page to rank
    },
}

SHELL = """<!doctype html>
<html lang="en-AU">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="description" content="{desc}">
<link rel="canonical" href="https://{domain}{path}">
{robots}
<meta property="og:type" content="website">
<meta property="og:site_name" content="Tradiesignal">
<meta property="og:title" content="{ogtitle}">
<meta property="og:description" content="{desc}">
<meta property="og:url" content="https://{domain}{path}">
<meta property="og:locale" content="en_AU">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{ogtitle}">
<meta name="twitter:description" content="{desc}">
<meta name="theme-color" content="#0A1628">
<link rel="icon" href="{favicon}">
<style>
  /* The Artifact host supplies a reset; standalone pages need their own. */
  html{{-webkit-text-size-adjust:100%}}
  body{{margin:0}}
  img{{max-width:100%}}
  [hidden]{{display:none!important}}
</style>
{head}
</head>
<body>
{body}
</body>
</html>
"""

NETLIFY_TOML = """# Tradiesignal :: Netlify configuration
# Static site. No build step — the HTML is generated by src/build_site.py and
# committed, so Netlify only has to publish it.

[build]
  publish = "deploy"
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), camera=(), microphone=()"

# The dashboard page is now a thin 34KB shell that fetches its rows, so it
# can be cached briefly. The data file must NOT be cached hard — a stale copy
# would show last week's projects while the page claims to be current.
[[headers]]
  for = "/demo/*"
  [headers.values]
    Cache-Control = "public, max-age=300, must-revalidate"

[[headers]]
  for = "/data/*.json"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "application/json; charset=utf-8"

# The PDF is regenerated weekly and linked from the report page.
[[headers]]
  for = "/*.pdf"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"

[[redirects]]
  from = "/report"
  to = "/sample-report/"
  status = 301

[[redirects]]
  from = "/dashboard"
  to = "/demo/"
  status = 301

[[redirects]]
  from = "/pricing"
  to = "/#pricing"
  status = 301
"""


def split_head_body(html: str) -> tuple[str, str]:
    """
    The builders emit <title>, <link rel=stylesheet>, <style> then markup.
    Everything up to the end of the last <style> belongs in <head>.
    """
    end = html.rfind("</style>")
    if end == -1:
        return "", html
    end += len("</style>")
    return html[:end], html[end:]


def rewire_ctas(html: str, checkout_url: str) -> str:
    """
    On the artifact the CTAs are on-page anchors. On the real site they should
    go to the sample report and to Stripe Checkout.
    """
    html = html.replace('href="#sample"', 'href="/sample-report/"')
    html = html.replace('href="#cta"', f'href="{checkout_url}"')
    # Keep the in-page pricing anchor, but point the plan buttons at Checkout.
    html = re.sub(
        r'<a class="btn (btn-blue|btn-go)" href="#cta">',
        lambda m: f'<a class="btn {m.group(1)}" href="{checkout_url}">',
        html,
    )
    return html


# A forwarded sample report is how this spreads through a trade group. Whoever
# opens it must be able to get back to the site and sign up without hunting.
REPORT_BAR = """
<div style="background:#0A1628;color:#EDF3FA;font-family:'IBM Plex Sans',system-ui,sans-serif;
  padding:11px 20px;display:flex;align-items:center;gap:14px;flex-wrap:wrap;
  border-bottom:2px solid #00E07A">
  <a href="/" style="font-family:Archivo,sans-serif;font-weight:800;font-size:18px;
    color:#fff;text-decoration:none;letter-spacing:-.03em">Tradie<span style="color:#00E07A">signal</span></a>
  <span style="font-size:12.5px;color:#93AEC9">Sample issue &middot; free to read and share</span>
  <span id="report-fresh" data-generated="{generated}"
    style="font-size:12.5px;color:#93AEC9"></span>
  <span style="margin-left:auto;display:flex;gap:9px;flex-wrap:wrap">
    <a href="/Tradiesignal-Hunter-Report.pdf" download
       style="font-size:13.5px;padding:8px 14px;border:1px solid #2E4E6B;border-radius:3px;
       color:#EDF3FA;text-decoration:none">Download PDF</a>
    <a href="{checkout}" style="font-size:13.5px;font-weight:700;padding:8px 16px;
       background:#00E07A;color:#04121F;border-radius:3px;text-decoration:none">Start free trial</a>
  </span>
</div>"""

REPORT_FOOT = """
<div style="background:#0A1628;color:#EDF3FA;font-family:'IBM Plex Sans',system-ui,sans-serif;
  padding:44px 20px;text-align:center;border-top:3px solid #00E07A">
  <h2 style="font-family:Archivo,sans-serif;font-weight:800;font-size:27px;color:#fff;
    margin:0 auto;max-width:22ch;line-height:1.15">You just read a fortnight of the Hunter's construction pipeline.</h2>
  <p style="margin:16px auto 0;max-width:52ch;color:#93AEC9;font-size:16px;line-height:1.55">
    This lands in your inbox every Monday at 6am, filtered to your patch and your
    sectors. Fourteen days free, no card, cancel by replying to any email.</p>
  <div style="margin-top:24px;display:flex;gap:11px;justify-content:center;flex-wrap:wrap">
    <a href="{checkout}" style="font-family:Archivo,sans-serif;font-weight:700;font-size:15px;
      padding:12px 24px;background:#00E07A;color:#04121F;border-radius:3px;
      text-decoration:none">Start free trial</a>
    <a href="/" style="font-family:Archivo,sans-serif;font-weight:700;font-size:15px;
      padding:12px 24px;border:2px solid #2E4E6B;color:#EDF3FA;border-radius:3px;
      text-decoration:none">How it works</a>
  </div>
  <p style="margin-top:22px;font-size:12.5px;color:#93AEC9">
    Know a sparky who'd use this? Forward it &mdash; if they subscribe you both get a month free.</p>
</div>"""


def add_demo_link(html: str) -> str:
    """Give the landing page a route into the dashboard demo."""
    return html.replace(
        '<a href="#faq">FAQ</a>',
        '<a href="/demo/">Dashboard demo</a>\n    <a href="#faq">FAQ</a>',
    )


FRESHNESS_JS = """
<script>
(function(){
  var el = document.getElementById("report-fresh");
  if (!el) return;
  var iso = el.dataset.generated;
  if (!iso) return;
  var days = Math.floor((Date.now() - Date.parse(iso)) / 864e5);
  var human = new Date(iso + "T00:00:00").toLocaleDateString("en-AU",
    { day: "numeric", month: "long", year: "numeric" });
  el.textContent = "\u00b7 Compiled " + human;
  // Say so rather than letting a stale page look current.
  if (days > 21) {
    el.textContent += " (" + days + " days ago)";
    el.style.color = "#E0A458";
    el.style.fontWeight = "600";
  }
})();
</script>"""


def build(domain: str, checkout_url: str) -> None:
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)

    import json
    payload_path = Path("data/report_payload.json")
    generated = (
        json.loads(payload_path.read_text(encoding="utf-8"))["generated"]
        if payload_path.exists() else ""
    )

    for out_name, meta in PAGES.items():
        raw = meta["src"].read_text(encoding="utf-8")
        head, body = split_head_body(raw)

        if meta["src"].name == "landing.html":
            body = add_demo_link(rewire_ctas(body, checkout_url))
        elif meta["src"].name == "report_web.html":
            body = (REPORT_BAR.format(checkout=checkout_url, generated=generated)
                    + body
                    + REPORT_FOOT.format(checkout=checkout_url)
                    + FRESHNESS_JS)

        # Strip the content-only <title>; the shell supplies a full one.
        title_match = re.search(r"<title>(.*?)</title>", head)
        og_title = title_match.group(1) if title_match else "Tradiesignal"
        head = re.sub(r"<title>.*?</title>", f"<title>{meta['title']}</title>", head, count=1)
        if "<title>" not in head:
            head = f"<title>{meta['title']}</title>" + head

        page = SHELL.format(
            desc=meta["desc"],
            domain=domain,
            path=meta["path"],
            ogtitle=og_title,
            favicon=FAVICON,
            robots="" if meta["index"] else '<meta name="robots" content="noindex,follow">',
            head=head,
            body=body,
        )

        target = OUT / out_name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(page, encoding="utf-8")
        print(f"  {out_name:28} {len(page):>9,} bytes")

    # The dashboard's project rows, fetched by the page at runtime. Refreshing
    # the site means replacing this one file, not rewriting the HTML.
    data_src = SITE / "dashboard-data.json"
    if data_src.exists():
        (OUT / "data").mkdir(parents=True, exist_ok=True)
        shutil.copy(data_src, OUT / "data" / "dashboard.json")
        print(f"  {'data/dashboard.json':28} {data_src.stat().st_size:>9,} bytes")

    # The PDF, so the sample-report page can offer a download.
    pdf = REPORTS / "Tradiesignal_Hunter_Report.pdf"
    if pdf.exists():
        shutil.copy(pdf, OUT / "Tradiesignal-Hunter-Report.pdf")
        print(f"  {'Tradiesignal-Hunter-Report.pdf':28} {pdf.stat().st_size:>9,} bytes")

    (OUT / "robots.txt").write_text(
        f"User-agent: *\nAllow: /\nDisallow: /demo/\n\nSitemap: https://{domain}/sitemap.xml\n",
        encoding="utf-8",
    )

    from datetime import date
    today = date.today().isoformat()
    urls = "".join(
        f"  <url><loc>https://{domain}{m['path']}</loc>"
        f"<lastmod>{today}</lastmod>"
        f"<changefreq>weekly</changefreq></url>\n"
        for m in PAGES.values() if m["index"]
    )
    (OUT / "sitemap.xml").write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        f"{urls}</urlset>\n",
        encoding="utf-8",
    )

    Path("netlify.toml").write_text(NETLIFY_TOML, encoding="utf-8")
    print("\n  robots.txt, sitemap.xml, netlify.toml written")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--domain", default="tradiesignal.com")
    ap.add_argument(
        "--checkout",
        default="#pricing",
        help="Stripe payment link. Until you have one, CTAs fall back to the pricing section.",
    )
    args = ap.parse_args()
    print(f"building deploy/ for {args.domain}")
    build(args.domain, args.checkout)


if __name__ == "__main__":
    main()
